-- Scheduler core tables ------------------------------------------------------

CREATE TABLE sch_job (
    id            BIGSERIAL PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    description   TEXT,
    job_type      VARCHAR(50)  NOT NULL,
    job_config    TEXT         NOT NULL,
    schedule_strategy_id BIGINT NOT NULL,
    precondition_config TEXT,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_time  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    BIGINT,
    updated_by    BIGINT
);

CREATE INDEX idx_sch_job_enabled ON sch_job(enabled);
CREATE INDEX idx_sch_job_type ON sch_job(job_type);

CREATE TABLE sch_schedule_strategy (
    id            BIGSERIAL PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    description   TEXT,
    schedule_type VARCHAR(50)  NOT NULL,
    cron_expression VARCHAR(255) NOT NULL,
    start_time    TIMESTAMP,
    end_time      TIMESTAMP,
    time_zone     VARCHAR(64),
    interval_seconds INTEGER,
    days_of_week  VARCHAR(32),
    created_time  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    BIGINT,
    updated_by    BIGINT
);

CREATE INDEX idx_sch_strategy_name ON sch_schedule_strategy(name);

CREATE TABLE sch_schedule_excluded_date (
    id          BIGSERIAL PRIMARY KEY,
    strategy_id BIGINT    NOT NULL REFERENCES sch_schedule_strategy(id) ON DELETE CASCADE,
    excluded_date DATE    NOT NULL,
    reason      VARCHAR(255),
    created_time  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    BIGINT,
    updated_by    BIGINT
);

CREATE INDEX idx_sch_excluded_strategy_date ON sch_schedule_excluded_date(strategy_id, excluded_date);

CREATE TABLE sch_job_execution_log (
    id                BIGSERIAL PRIMARY KEY,
    job_id            BIGINT     NOT NULL REFERENCES sch_job(id) ON DELETE CASCADE,
    strategy_id       BIGINT     NOT NULL REFERENCES sch_schedule_strategy(id) ON DELETE CASCADE,
    scheduled_fire_time TIMESTAMP NOT NULL,
    actual_fire_time  TIMESTAMP  NOT NULL,
    finished_time     TIMESTAMP,
    status            VARCHAR(20) NOT NULL,
    error_message     VARCHAR(2000),
    retry_count       INTEGER    NOT NULL DEFAULT 0,
    duration_ms       INTEGER,
    created_time      TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time      TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by        BIGINT,
    updated_by        BIGINT
);

CREATE INDEX idx_sch_log_job ON sch_job_execution_log(job_id, scheduled_fire_time);
CREATE INDEX idx_sch_log_status ON sch_job_execution_log(status);
CREATE INDEX idx_sch_log_strategy ON sch_job_execution_log(strategy_id);

-- Quartz JDBC tables (based on the official Quartz schema for PostgreSQL) ----

CREATE TABLE sch_qrtz_job_details(
    SCHED_NAME VARCHAR(120) NOT NULL,
    JOB_NAME VARCHAR(200) NOT NULL,
    JOB_GROUP VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(250),
    JOB_CLASS_NAME VARCHAR(250) NOT NULL,
    IS_DURABLE BOOLEAN NOT NULL,
    IS_NONCONCURRENT BOOLEAN NOT NULL,
    IS_UPDATE_DATA BOOLEAN NOT NULL,
    REQUESTS_RECOVERY BOOLEAN NOT NULL,
    JOB_DATA BYTEA,
    PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
);

CREATE TABLE sch_qrtz_triggers(
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    JOB_NAME VARCHAR(200) NOT NULL,
    JOB_GROUP VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(250),
    NEXT_FIRE_TIME BIGINT,
    PREV_FIRE_TIME BIGINT,
    PRIORITY INTEGER,
    TRIGGER_STATE VARCHAR(16) NOT NULL,
    TRIGGER_TYPE VARCHAR(8) NOT NULL,
    START_TIME BIGINT NOT NULL,
    END_TIME BIGINT,
    CALENDAR_NAME VARCHAR(200),
    MISFIRE_INSTR SMALLINT,
    JOB_DATA BYTEA,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
      REFERENCES sch_qrtz_job_details(SCHED_NAME,JOB_NAME,JOB_GROUP)
);

CREATE TABLE sch_qrtz_simple_triggers(
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    REPEAT_COUNT BIGINT NOT NULL,
    REPEAT_INTERVAL BIGINT NOT NULL,
    TIMES_TRIGGERED BIGINT NOT NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES sch_qrtz_triggers(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        ON DELETE CASCADE
);

CREATE TABLE sch_qrtz_cron_triggers(
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    CRON_EXPRESSION VARCHAR(120) NOT NULL,
    TIME_ZONE_ID VARCHAR(80),
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES sch_qrtz_triggers(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        ON DELETE CASCADE
);

CREATE TABLE sch_qrtz_simprop_triggers(
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    STR_PROP_1 VARCHAR(512),
    STR_PROP_2 VARCHAR(512),
    STR_PROP_3 VARCHAR(512),
    INT_PROP_1 INTEGER,
    INT_PROP_2 INTEGER,
    LONG_PROP_1 BIGINT,
    LONG_PROP_2 BIGINT,
    DEC_PROP_1 NUMERIC(13,4),
    DEC_PROP_2 NUMERIC(13,4),
    BOOL_PROP_1 BOOLEAN,
    BOOL_PROP_2 BOOLEAN,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES sch_qrtz_triggers(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        ON DELETE CASCADE
);

CREATE TABLE sch_qrtz_blob_triggers(
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    BLOB_DATA BYTEA,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES sch_qrtz_triggers(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        ON DELETE CASCADE
);

CREATE TABLE sch_qrtz_calendars(
    SCHED_NAME VARCHAR(120) NOT NULL,
    CALENDAR_NAME VARCHAR(200) NOT NULL,
    CALENDAR BYTEA NOT NULL,
    PRIMARY KEY (SCHED_NAME,CALENDAR_NAME)
);

CREATE TABLE sch_qrtz_paused_trigger_grps (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP)
);

CREATE TABLE sch_qrtz_fired_triggers (
    SCHED_NAME VARCHAR(120) NOT NULL,
    ENTRY_ID VARCHAR(140) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    INSTANCE_NAME VARCHAR(200) NOT NULL,
    FIRED_TIME BIGINT NOT NULL,
    SCHED_TIME BIGINT NOT NULL,
    PRIORITY INTEGER NOT NULL,
    STATE VARCHAR(16) NOT NULL,
    JOB_NAME VARCHAR(200),
    JOB_GROUP VARCHAR(200),
    IS_NONCONCURRENT BOOLEAN,
    REQUESTS_RECOVERY BOOLEAN,
    PRIMARY KEY (SCHED_NAME,ENTRY_ID)
);

CREATE TABLE sch_qrtz_scheduler_state (
    SCHED_NAME VARCHAR(120) NOT NULL,
    INSTANCE_NAME VARCHAR(200) NOT NULL,
    LAST_CHECKIN_TIME BIGINT NOT NULL,
    CHECKIN_INTERVAL BIGINT NOT NULL,
    PRIMARY KEY (SCHED_NAME,INSTANCE_NAME)
);

CREATE TABLE sch_qrtz_locks (
    SCHED_NAME VARCHAR(120) NOT NULL,
    LOCK_NAME VARCHAR(40) NOT NULL,
    PRIMARY KEY (SCHED_NAME,LOCK_NAME)
);

CREATE INDEX idx_sch_qrtz_j_req_recovery ON sch_qrtz_job_details(SCHED_NAME,REQUESTS_RECOVERY);
CREATE INDEX idx_sch_qrtz_j_grp ON sch_qrtz_job_details(SCHED_NAME,JOB_GROUP);
CREATE INDEX idx_sch_qrtz_t_j ON sch_qrtz_triggers(SCHED_NAME,JOB_NAME,JOB_GROUP);
CREATE INDEX idx_sch_qrtz_t_jg ON sch_qrtz_triggers(SCHED_NAME,JOB_GROUP);
CREATE INDEX idx_sch_qrtz_t_c ON sch_qrtz_triggers(SCHED_NAME,CALENDAR_NAME);
CREATE INDEX idx_sch_qrtz_t_g ON sch_qrtz_triggers(SCHED_NAME,TRIGGER_GROUP);
CREATE INDEX idx_sch_qrtz_t_state ON sch_qrtz_triggers(SCHED_NAME,TRIGGER_STATE);
CREATE INDEX idx_sch_qrtz_t_n_state ON sch_qrtz_triggers(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP,TRIGGER_STATE);
CREATE INDEX idx_sch_qrtz_t_next_fire_time ON sch_qrtz_triggers(SCHED_NAME,NEXT_FIRE_TIME);
CREATE INDEX idx_sch_qrtz_t_nft_st ON sch_qrtz_triggers(SCHED_NAME,TRIGGER_STATE,NEXT_FIRE_TIME);
CREATE INDEX idx_sch_qrtz_t_nft_misfire ON sch_qrtz_triggers(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME);
CREATE INDEX idx_sch_qrtz_t_nft_st_misfire ON sch_qrtz_triggers(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_STATE);
CREATE INDEX idx_sch_qrtz_t_nft_st_misfire_grp ON sch_qrtz_triggers(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_GROUP,TRIGGER_STATE);
CREATE INDEX idx_sch_qrtz_ft_trig_inst_name ON sch_qrtz_fired_triggers(SCHED_NAME,INSTANCE_NAME);
CREATE INDEX idx_sch_qrtz_ft_inst_job_req_rcvry ON sch_qrtz_fired_triggers(SCHED_NAME,INSTANCE_NAME,REQUESTS_RECOVERY);
CREATE INDEX idx_sch_qrtz_ft_j_g ON sch_qrtz_fired_triggers(SCHED_NAME,JOB_NAME,JOB_GROUP);
CREATE INDEX idx_sch_qrtz_ft_jg ON sch_qrtz_fired_triggers(SCHED_NAME,JOB_GROUP);
CREATE INDEX idx_sch_qrtz_ft_t_g ON sch_qrtz_fired_triggers(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);
CREATE INDEX idx_sch_qrtz_ft_tg ON sch_qrtz_fired_triggers(SCHED_NAME,TRIGGER_GROUP);
